apiVersion: apps/v1
kind: ReplicaSet
metadata:
	name: nginx-replicaset
spec:
	selector:
	  matchLabels:
      app: nginx
  template:
    metadata:
	    labels:
		    app: nginx
    spec:
      replicas: 10
	    containers:
	    - name: nginx
	      image: nginx
		    ports:
        - containerPort: 80